[project]
name = 'Dyson-Sphere-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dyson-construction]
path = 'contracts/dyson-construction.clar'
clarity_version = 2
epoch = 2.5

[contracts.dyson-governance]
path = 'contracts/dyson-governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.dyson-investment]
path = 'contracts/dyson-investment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
